llm:
  embedding_model:
    model_name: "text-embedding-nomic-embed-text-v1.5@q5_0"
  llm_model:
    model_name: "llama-3.3-70b-instruct"

local_deployment_api:
  api_key: "lm_studio"
  api_base: "http://127.0.0.1:1234/v1"